[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
cgmath = "0.18"
js-sys = "0.3"
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3" }
glam = "0.22"
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"
once_cell = "1.16"
env_logger = "0.10"
log = "0.4"
criterion = { version = "0.4", features = ["html_reports"] }

[profile.bench]
debug = true

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
strip = true
